// Generated by CoffeeScript 1.7.1
var editor;

editor = new JSONEditor(document.getElementById("editor"), {
  theme: "bootstrap3",
  iconlib: "fontawesome4",
  disable_edit_json: true,
  disable_properties: true,
  schema: {
    title: "基本情報",
    type: "object",
    properties: {
      count: {
        title: "連数",
        type: "integer",
        "default": 3,
        minimum: 1,
        maximum: 10
      },
      side: {
        title: "面",
        type: "integer",
        "default": 1,
        minimum: 1,
        maximum: 2
      },
      angle: {
        title: "角度",
        type: "integer",
        "default": 0,
        minimum: 0,
        maximum: 360
      }
    }
  }
});

editor.on("change", function() {
  var data, errors, key, object;
  errors = editor.validate();
  if (errors.length) {
    alert('入力値が正しくありません。');
  } else {
    data = editor.getValue();
    object = app.canvas.getActiveObject();
    if (object) {
      for (key in editor.schema.properties) {
        object[key] = data[key];
      }
      app.render();
      $(app.canvas.getObjects()).each((function(_this) {
        return function(i, obj) {
          if (obj.id === object.id) {
            return app.canvas.setActiveObject(obj);
          }
        };
      })(this));
    }
  }
});

//# sourceMappingURL=editor.map
