// Generated by CoffeeScript 1.7.1
var editor;

editor = new JSONEditor(document.getElementById("editor"), {
  theme: "bootstrap3",
  iconlib: "fontawesome4",
  disable_edit_json: true,
  disable_properties: true,
  schema: {
    title: "基本情報",
    type: "object",
    properties: {
      count: {
        type: "integer",
        "default": 3,
        minimum: 1,
        maximum: 10
      },
      side: {
        type: "integer",
        "default": 1,
        minimum: 1,
        maximum: 2
      },
      shelfs: {
        type: "array",
        uniqueItems: true,
        items: {
          type: "string",
          "enum": ["value1", "value2"]
        }
      }
    }
  }
});

editor.on("change", function() {
  var data, errors, key, object;
  errors = editor.validate();
  if (errors.length) {
    alert('Not validate');
  } else {
    data = editor.getValue();
    object = app.canvas.getActiveObject();
    if (object) {
      for (key in editor.schema.properties) {
        object[key] = data[key];
      }
      app.render();
    }
  }
});

//# sourceMappingURL=editor.map
