// Generated by CoffeeScript 1.7.1
var center, geojson, image, map, styleFunction, styles, vectorLayer, vectorSource;

image = new ol.style.Circle({
  radius: 5,
  fill: null,
  stroke: new ol.style.Stroke({
    color: "blue",
    width: 1
  })
});

styles = {
  Point: [
    new ol.style.Style({
      image: image
    })
  ],
  LineString: [
    new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: "green",
        width: 1
      })
    })
  ],
  MultiLineString: [
    new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: "green",
        width: 1
      })
    })
  ],
  MultiPoint: [
    new ol.style.Style({
      image: image
    })
  ],
  MultiPolygon: [
    new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: "yellow",
        width: 1
      }),
      fill: new ol.style.Fill({
        color: "rgba(255, 255, 0, 0.1)"
      })
    })
  ],
  Polygon: [
    new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: "red",
        lineDash: [4],
        width: 3
      }),
      fill: new ol.style.Fill({
        color: "rgba(255, 0, 0, 0.1)"
      })
    })
  ],
  GeometryCollection: [
    new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: "magenta",
        width: 2
      }),
      fill: new ol.style.Fill({
        color: "magenta"
      }),
      image: new ol.style.Circle({
        radius: 10,
        fill: null,
        stroke: new ol.style.Stroke({
          color: "magenta"
        })
      })
    })
  ],
  Circle: [
    new ol.style.Style({
      stroke: new ol.style.Stroke({
        color: "red",
        width: 2
      }),
      fill: new ol.style.Fill({
        color: "rgba(255,0,0,0.2)"
      })
    })
  ]
};

styleFunction = function(feature, resolution) {
  return styles[feature.getGeometry().getType()];
};


/*
@type {olx.source.GeoJSONOptions}
 */

geojson = localStorage.getItem('geojson');

console.log(geojson);

vectorSource = new ol.source.GeoJSON({
  object: {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              138.6968994140625,
              35.36665566526249
            ],
            [
              138.6968994140625,
              35.97800618085568
            ],
            [
              140.1910400390625,
              35.97800618085568
            ],
            [
              140.1910400390625,
              35.36665566526249
            ],
            [
              138.6968994140625,
              35.36665566526249
            ]
          ]
        ]
      }
    }
  ]
}
});

var features = vectorSource.getFeatures();
console.log(features);

vectorLayer = new ol.layer.Vector({
  source: vectorSource,
//  style: styleFunction
});

center = ol.proj.transform([139.761239, 35.697086], "EPSG:4326", "EPSG:3857");

map = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM()
    }), vectorLayer
  ],
  target: "map",
  view: new ol.View2D({
    center: center,
    zoom: 2
  })
});

//# sourceMappingURL=geojsonmap.map
