// Generated by CoffeeScript 1.7.1
$('#bgimg').change(function(e) {
  var data, files;
  files = e.target.files;
  if (files.length === 0) {
    return;
  }
  if (haika.isLocal()) {
    return haika.loadBgFromFile(files[0]);
  } else {
    data = new FormData();
    data.append('id', haika.id);
    data.append('userfile', files[0]);
    return $.ajax({
      url: '/haika_store/upload.php',
      data: data,
      cache: false,
      contentType: false,
      processData: false,
      type: 'POST',
      success: function(data) {
        var url;
        url = '/haika_store/image/' + haika.id + '_' + files[0].name;
        return haika.loadBgFromUrl(url);
      }
    });
  }
});

$(function() {
  $(".add_custom_shelf").click(function() {
    add('custom_shelf');
    return haika.render();
  });
  $(".add_beacon").click(function() {
    add('beacon');
    return haika.render();
  });
  $(".remove").click(function() {
    var object;
    object = haika.canvas.getActiveObject();
    haika.remove();
    if (object) {
      return undo.remove(object);
    }
  });
  $(".zoomin").click(function() {
    return haika.zoomIn();
  });
  $(".zoomout").click(function() {
    return haika.zoomOut();
  });
  $(".zoomreset").click(function() {
    return haika.zoomReset();
  });
  $(".bringtofront").click(function() {
    return haika.bringToFront();
  });
  $(".duplicate").click(function() {
    return haika.duplicate();
  });
  $(".copy").click(function() {
    return haika.copy();
  });
  $(".paste").click(function() {
    return haika.paste();
  });
  $(".align-left").click(function() {
    return haika.alignLeft();
  });
  $(".align-center").click(function() {
    return haika.alignCenter();
  });
  $(".align-right").click(function() {
    return haika.alignRight();
  });
  $(".align-top").click(function() {
    return haika.alignTop();
  });
  $(".align-vcenter").click(function() {
    return haika.alignVcenter();
  });
  return $(".align-bottom").click(function() {
    return haika.alignBottom();
  });
});

$(function() {
  var cancel_default, map_created, timeout, toggle_map;
  timeout = false;
  $('canvas').on('mousewheel', (function(_this) {
    return function(event) {
      if (timeout) {
        return;
      } else {
        timeout = setTimeout(function() {
          return timeout = false;
        }, 100);
      }
      if (event.deltaY > 0) {
        haika.zoomIn();
      }
      if (event.deltaY < 0) {
        return haika.zoomOut();
      }
    };
  })(this));
  $('#canvas_width').change(function() {
    return haika.canvas.setWidth($(this).val());
  });
  $('#canvas_height').change(function() {
    return haika.canvas.setHeight($(this).val());
  });
  $('#canvas_centerX').change(function() {
    return haika.centerX = parseInt($(this).val());
  });
  $('#canvas_centerY').change(function() {
    return haika.centerY = parseInt($(this).val());
  });
  $('#canvas_bgscale').change(function() {
    return haika.options.bgscale = parseFloat($(this).val());
  });
  $('#ex1').slider({
    formater: function(value) {
      value = parseFloat(value).toFixed(1);
      $('#canvas_bgopacity').val();
      haika.options.bgopacity = value;
      haika.render();
      return value;
    }
  });
  $('#canvas_render').click(function() {
    return haika.render();
  });
  $('#canvas_lat').change(function() {
    haika.options.lat = parseFloat($(this).val());
    return haika.save();
  });
  $('#canvas_lon').change(function() {
    haika.options.lon = parseFloat($(this).val());
    return haika.save();
  });
  $('#canvas_angle').change(function() {
    haika.options.angle = parseInt($(this).val());
    return haika.save();
  });
  map_created = false;
  toggle_map = function() {
    if ($('.haika_container').css('display') === 'block') {
      if (!map_created) {
        map_setting();
        map_created = true;
      }
      $('.haika_container').hide();
      $('.map_container').show();
      return $('#map_query').focus();
    } else {
      $('.haika_container').show();
      return $('.map_container').hide();
    }
  };
  $('.map_setting').click(toggle_map);
  $('.undo').click(function() {
    return undo.undoManager.undo();
  });
  cancel_default = function(e) {
    if (e.preventDefault) {
      return e.preventDefault();
    } else {
      return e.returnValue = false;
    }
  };
  Mousetrap.bind('mod+o', function() {
    $('#file').trigger('click');
    return false;
  });
  Mousetrap.bind('mod+c', function() {
    haika.copy();
    return false;
  });
  Mousetrap.bind('mod+v', function() {
    haika.paste();
    return false;
  });
  Mousetrap.bind('mod+d', function(e) {
    cancel_default(e);
    haika.duplicate();
    return false;
  });
  Mousetrap.bind('mod+a', function(e) {
    cancel_default(e);
    haika.selectAll();
    return false;
  });
  Mousetrap.bind('mod+z', function(e) {
    cancel_default(e);
    undo.undoManager.undo();
    return false;
  });
  Mousetrap.bind(['esc', 'escape'], function(e) {
    cancel_default(e);
    haika.unselectAll();
    return false;
  });
  Mousetrap.bind(['up', 'shift+up'], function(e) {
    cancel_default(e);
    haika.up(e);
    return false;
  });
  Mousetrap.bind(['down', 'shift+down'], function(e) {
    cancel_default(e);
    haika.down(e);
    return false;
  });
  Mousetrap.bind(['left', 'shift+left'], function(e) {
    cancel_default(e);
    haika.left(e);
    return false;
  });
  Mousetrap.bind(['right', 'shift+right'], function(e) {
    cancel_default(e);
    haika.right(e);
    return false;
  });
  return $(document).unbind("keydown").bind("keydown", function(event) {
    var d, doPrevent;
    doPrevent = false;
    if (event.keyCode === 8 || event.keyCode === 46) {
      d = event.srcElement || event.target;
      if ((d.tagName.toUpperCase() === "INPUT" && (d.type.toUpperCase() === "TEXT" || d.type.toUpperCase() === "PASSWORD" || d.type.toUpperCase() === "FILE" || d.type.toUpperCase() === "EMAIL")) || d.tagName.toUpperCase() === "TEXTAREA") {
        doPrevent = d.readOnly || d.disabled;
      } else {
        doPrevent = true;
      }
    }
    if (doPrevent) {
      event.preventDefault();
      haika.remove();
    }
  });
});

/*
//@ sourceMappingURL=haika.event.map
*/
