// Generated by CoffeeScript 1.7.1
var map_setting;

map_setting = function() {
  var center, featureStyle, features, geojson, gmap, image, olMapDiv, styleFunction, styles, vectorLayer, vectorSource, view;
  gmap = new google.maps.Map(document.getElementById("gmap"), {
    disableDefaultUI: true,
    keyboardShortcuts: false,
    draggable: false,
    disableDoubleClickZoom: true,
    scrollwheel: false,
    streetViewControl: false
  });
  featureStyle = {
    fillColor: 'orange',
    strokeWeight: 1
  };
  gmap.data.setStyle(featureStyle);
  gmap.data.loadGeoJson('data/000087.geojson');
  image = new ol.style.Circle({
    radius: 5,
    fill: null,
    stroke: new ol.style.Stroke({
      color: "blue",
      width: 1
    })
  });
  styles = {
    Point: [
      new ol.style.Style({
        image: image
      })
    ],
    LineString: [
      new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: "green",
          width: 1
        })
      })
    ],
    MultiLineString: [
      new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: "green",
          width: 1
        })
      })
    ],
    MultiPoint: [
      new ol.style.Style({
        image: image
      })
    ],
    MultiPolygon: [
      new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: "yellow",
          width: 1
        }),
        fill: new ol.style.Fill({
          color: "rgba(255, 255, 0, 0.1)"
        })
      })
    ],
    Polygon: [
      new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: "red",
          width: 3
        }),
        fill: new ol.style.Fill({
          color: "rgba(255, 0, 0, 0.1)"
        })
      })
    ],
    GeometryCollection: [
      new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: "magenta",
          width: 2
        }),
        fill: new ol.style.Fill({
          color: "magenta"
        }),
        image: new ol.style.Circle({
          radius: 10,
          fill: null,
          stroke: new ol.style.Stroke({
            color: "magenta"
          })
        })
      })
    ],
    Circle: [
      new ol.style.Style({
        stroke: new ol.style.Stroke({
          color: "red",
          width: 2
        }),
        fill: new ol.style.Fill({
          color: "rgba(255,0,0,0.2)"
        })
      })
    ]
  };
  styleFunction = function(feature, resolution) {
    return styles[feature.getGeometry().getType()];
  };
  geojson = app.toGeoJSON();
  log(geojson);
  vectorSource = new ol.source.GeoJSON({
    object: geojson
  });
  features = vectorSource.getFeatures();
  console.log(features);
  vectorLayer = new ol.layer.Vector({
    source: vectorSource,
    style: styleFunction
  });
  center = ol.proj.transform([app.options.lon, app.options.lat], "EPSG:4326", "EPSG:3857");
  view = new ol.View2D({
    layers: [vectorLayer],
    center: center,
    zoom: 2,
    maxZoom: 21
  });
  view.on("change:center", function() {
    center = ol.proj.transform(view.getCenter(), "EPSG:3857", "EPSG:4326");
    return gmap.setCenter(new google.maps.LatLng(center[1], center[0]));
  });
  view.on("change:resolution", function() {
    return gmap.setZoom(view.getZoom());
  });
  olMapDiv = document.getElementById("olmap");
  window.map = new ol.Map({
    target: "map",
    ol3Logo: false,
    layers: [vectorLayer],
    interactions: ol.interaction.defaults({
      altShiftDragRotate: false,
      dragPan: false,
      rotate: false
    }).extend([
      new ol.interaction.DragPan({
        kinetic: null
      })
    ]),
    target: olMapDiv,
    view: view
  });
  view.setCenter(center);
  view.setZoom(20);
  olMapDiv.parentNode.removeChild(olMapDiv);
  gmap.controls[google.maps.ControlPosition.TOP_LEFT].push(olMapDiv);
  return map.on('moveend', function(e) {
    var new_center;
    center = map.getView().getCenter();
    new_center = ol.proj.transform(center, "EPSG:3857", "EPSG:4326");
    $('#canvas_lon').val(new_center[0]);
    app.options.lon = new_center[0];
    $('#canvas_lat').val(new_center[1]);
    app.options.lat = new_center[1];
    return app.save();
  });
};

$('#map_search').submit(function() {
  var url;
  url = 'http://nominatim.openstreetmap.org/search';
  $.ajax({
    url: url,
    type: "GET",
    data: {
      q: $('#map_query').val(),
      format: "json"
    },
    dataType: "jsonp",
    jsonp: "json_callback",
    error: function() {},
    success: (function(_this) {
      return function(data) {
        var center, view;
        log(data);
        if (data.length > 0) {
          app.options.lon = parseFloat(data[0].lon);
          app.options.lat = parseFloat(data[0].lat);
          app.save();
          $('#canvas_lon').val(app.options.lon);
          $('#canvas_lat').val(app.options.lat);
          center = ol.proj.transform([app.options.lon, app.options.lat], "EPSG:4326", "EPSG:3857");
          view = map.getView();
          view.setCenter(center);
          return view.setZoom(20);
        } else {
          return alert('見つかりませんでした。');
        }
      };
    })(this)
  });
  return false;
});

/*
//@ sourceMappingURL=map_setting.map
*/
