// Generated by CoffeeScript 1.7.1
describe('mochaのテスト', function() {
  it('1 + 1 は2になること', function() {
    assert(1 + 1, 2);
  });
  it('failするテスト', function() {
    assert.ok(false);
  });
  it('後で書く');
  it('haikaオブジェクトはあるか', function() {
    return expect(haika).to.be.a('Object');
  });
  it('haikaのstate値はshelfか', function() {
    return expect(haika.state).to.eql('shelf');
  });
  return it('haikaのwidth値は800か', function() {
    return expect(haika.width > 600).to.be.ok();
  });
});

/*
//@ sourceMappingURL=test.map
*/
