// Generated by CoffeeScript 1.9.1
"use strict";
module.exports = function(grunt) {
  var js_files;
  js_files = ["bower_components/fabric/dist/fabric.js", "bower_components/Javascript-Undo-Manager/js/undomanager.js", "bower_components/seiyria-bootstrap-slider/dist/bootstrap-slider.min.js", "bower_components/bootstrap-contextmenu/bootstrap-contextmenu.js", "vendor/mousetrap.min.js", "vendor/dragdealer/dragdealer.min.js", "vendor/graham_scan_js-1.0.2/graham_scan.min.js", "vendor/clipper_unminified.js", "src/fabric_object/aligning_guidelines.js", "src/fabric_object/shelf.js", "src/fabric_object/curvedShelf.js", "src/fabric_object/beacon.js", "src/fabric_object/wall.js", "src/fabric_object/floor.js", "src/fabric_object/grid.js", "src/haika.js", "src/haika-io.js", "src/haika-geojson.js", "src/haika-zoom.js", "src/haika-scrollbar.js", "src/haika-toolbar.js", "src/haika-event.js", "src/haika-undo.js", "src/haika-property.js", "src/haika-html.js"];
  grunt.initConfig({
    pkg: grunt.file.readJSON("package.json"),
    bower: {
      install: {
        options: {
          install: true,
          copy: false,
          cleanTargetDir: false,
          cleanBowerDir: false
        }
      }
    },
    coffee: {
      compile: {
        options: {
          sourceMap: true,
          bare: true
        },
        expand: true,
        flatten: true,
        cwd: 'src/',
        src: ['*.coffee'],
        dest: 'src/',
        ext: '.js'
      }
    },
    concat: {
      js: {
        options: {
          stripBanners: true,
          separator: ";"
        },
        src: js_files,
        dest: "dist/haika.all.js",
        nonull: true
      },
      css: {
        src: ["vendor/dragdealer/dragdealer.css", "bower_components/seiyria-bootstrap-slider/dist/css/bootstrap-slider.min.css", "css/haika.css"],
        dest: "css/haika.all.css",
        nonull: true
      }
    },
    cssmin: {
      minify: {
        expand: true,
        cwd: 'css/',
        src: ['haika.all.css', '!*.min.css'],
        dest: 'css/',
        ext: '.min.css',
        options: {
          noAdvanced: true
        }
      }
    },
    uglify: {
      options: {
        banner: "/*! <%= pkg.name %> <%= grunt.template.today(\"dd-mm-yyyy\") %> */\n"
      },
      dist: {
        files: {
          "dist/haika.all.min.js": ["dist/haika.all.js"]
        }
      }
    }
  });
  require('load-grunt-tasks')(grunt);
  return grunt.registerTask("default", ["bower", "coffee", "concat", "uglify"]);
};

//# sourceMappingURL=Gruntfile.js.map
