// Generated by CoffeeScript 1.8.0
$(haika).on('haika:render', function() {
  $('#canvas_width').html(haika.canvas.getWidth());
  $('#canvas_height').html(haika.canvas.getHeight());
  $('#canvas_centerX').html(haika.centerX);
  $('#canvas_centerY').html(haika.centerY);
  $('#canvas_bgscale').val(haika.backgroundScaleFactor);
  $('#canvas_bgopacity').val(haika.backgroundOpacity);
  $('#canvas_lon').val(haika.xyLongitude);
  $('#canvas_lat').val(haika.xyLatitude);
  $('#canvas_angle').val(haika.canvas.angle);
  return $('.zoom').html((haika.scaleFactor * 100).toFixed(0) + '%');
});

$(haika).on('haika:initialized', function() {
  return haika.openFromApi(2, {
    success: function() {
      return haika.render();
    },
    error: function(message) {
      return alert(message);
    }
  });
});

$('.fullscreen').click(function() {
  if ($('.haika-container')[0].requestFullScreen) {
    $('.haika-container')[0].requestFullScreen();
  }
  if ($('.haika-container')[0].webkitRequestFullScreen) {
    $('.haika-container')[0].webkitRequestFullScreen();
  }
  if ($('.haika-container')[0].mozRequestFullScreen) {
    return $('.haika-container')[0].mozRequestFullScreen();
  }
});

haika.init({
  divId: 'haika-canvas'
});

if (haika.readOnly) {
  haika.event.zoom();
} else {
  haika.toolbar.init();
  haika.event.init();
  haika.undo.init();
  initScrollBar();
  haika.map.initMap();
  haika.colorpicker.init();
}

//# sourceMappingURL=sample.js.map
